resources:
- name: osp_test_resource
  type: git
  source:
    uri: https://github.com/godleon/concourse_ci_lab
    branch: master

jobs:
- name: tempest-rally-test
  public: true
  plan:
  
  - get: osp_test_resource
    trigger: true
  
  - task: tempest
    file: osp_test_resource/06.osp10_tempest_rally/build_tasks/tempest_test.yml

  - task: rally
    file: osp_test_resource/06.osp10_tempest_rally/build_tasks/rally_test.yml

# - name: rally-test
#   public: true
#   plan:
#   - get: osp_test_resource
#     trigger: true
#     passed: [tempest]
#       params:
#       bump: minor
#     rc: true
#   - task: rally
#     file: osp_test_resource/06.osp10_tempest_rally/build_tasks/rally_test.yml