platform: linux

image_resource:
  type: docker-image
  source: 
    repository: registry.access.redhat.com/rhel7.3

inputs:
- name: tempest_config

run:
  path: sh
  args:
    - -exc
    - |
      find / | grep tempest