platform: linux

image_resource:
  type: docker-image
  source: 
    repository: registry.access.redhat.com/rhel7.3

inputs:
- name: osp_test_resource

run:
  path: sh
  args:
    - -exc
    - |
      source osp_test_resource/03.osp10_tempest/scripts/env_var.list
      echo "REDHAT_USERNAME=${REDHAT_USERNAME}"
      echo "REDHAT_USERPASSWORD=${REDHAT_USERPASSWORD}"
      echo "OS_AUTH_URL=${OS_AUTH_URL}"
      bash osp_test_resource/03.osp10_tempest/scripts/prepare_env.sh