platform: linux

image_resource:
  type: docker-image
  source: 
    repository: registry.access.redhat.com/rhel7.3

inputs:
- name: osp_test_resource

run:
  path: sh
  args:
    - -exc
    - |
      pwd
      bash osp_test_resource/03.osp10_tempest/scripts/prepare_env.sh