# resource_types:

# - name: slack-notification
#   type: docker-image
#   source:
#     repository: cfcommunity/slack-notification-resource
#     tag: latest

resources:

- name: git_osp
  type: git
  check_every: 30s
  source:
    uri: {{git-uri_osp}}
    branch: master
    private_key: {{git-private-key}}

# - name: git-display
#   type: git
#   source:
#     uri: {{git-uri_test-result}}
#     branch: gh-pages
#     private_key: {{git-private-key}}

- name: rally_test
  type: git
  check_every: 30s
  source:
    uri: {{git-uri_test-result}}
    branch: rally_test
    private_key: {{git-private-key}}
    
- name: rally_result
  type: git
  source:
    uri: {{git-uri_test-result}}
    branch: rally_result
    private_key: {{git-private-key}}

- name: git_semver
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri_test-result}}
    branch: version
    file: version
    private_key: {{git-private-key}}

# - name: slack
#   type: slack-notification
#   source:
#     url: https://hooks.slack.com/services/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

jobs:

- name: rally_init
  plan:
  - aggregate:
    - get: git_osp
      trigger: true
    - get: rally_test
    - get: git_semver
      params: {bump: patch}
  - task: propagate_rally_tests
    file: git_osp/09.rally/build_tasks/propagate_rally_tests.yml
  - put: rally_test
    params: {repository: propagated_tests}
  - put: git_semver
    params: {file: git_semver/version}

- name: rally_test
  plan:
  - aggregate:
    - get: git_osp
    - get: rally_test
      trigger: true
      passed: [rally_init]
    - get: rally_result
    - get: git_semver
  - task: run_test
    privileged: true
    params:
      OS_AUTH_URL: {{OS_AUTH_URL}}
      OS_USERNAME: {{OS_USERNAME}}
      OS_PASSWORD: {{OS_PASSWORD}}
      OS_TENANT_NAME: {{OS_TENANT_NAME}}
    file: git_osp/09.rally/build_tasks/run_test.yml
  - put: rally_test
    params: {repository: rally_remain_tests}