# resource_types:

# - name: slack-notification
#   type: docker-image
#   source:
#     repository: cfcommunity/slack-notification-resource
#     tag: latest

resources:

- name: git-osp
  type: git
  source:
    uri: {{git-uri_osp}}
    branch: master
    private_key: {{git-private-key}}

- name: git-results
  type: git
  source:
    uri: {{git-uri_test-result}}
    branch: gh-pages
    private_key: {{git-private-key}}

- name: git-semver
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri_test-result}}
    branch: version
    file: version
    private_key: {{git-private-key}}

# - name: slack
#   type: slack-notification
#   source:
#     url: https://hooks.slack.com/services/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

jobs:

- name: Keystone
  plan:
  - aggregate:
    - get: git-osp
      trigger: true
    - get: git-semver
    - get: git-results
  - task: keystone-benchmark
    privileged: true
    file: git-osp/09.rally/build_tasks/keystone_benchmark.yml
    params:
      OS_AUTH_URL: {{OS_AUTH_URL}}
      OS_USERNAME: {{OS_USERNAME}}
      OS_PASSWORD: {{OS_PASSWORD}}
      OS_TENANT_NAME: {{OS_TENANT_NAME}}
  # - put: git-resource_build
  #   params: {repository: tempest_output}