# resource_types:

# - name: slack-notification
#   type: docker-image
#   source:
#     repository: cfcommunity/slack-notification-resource
#     tag: latest

resources:

- name: git-osp
  type: git
  check_every: 30s
  source:
    uri: {{git-uri_osp}}
    branch: master
    private_key: {{git-private-key}}

# - name: git-display
#   type: git
#   source:
#     uri: {{git-uri_test-result}}
#     branch: gh-pages
#     private_key: {{git-private-key}}

- name: rally_test
  type: git
  check_every: 30s
  source:
    uri: {{git-uri_test-result}}
    branch: rally_test
    private_key: {{git-private-key}}
    
# - name: rally_result
#   type: git
#   source:
#     uri: {{git-uri_test-result}}
#     branch: rally_result
#     private_key: {{git-private-key}}

- name: git-semver
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri_test-result}}
    branch: version
    file: version
    private_key: {{git-private-key}}

# - name: slack
#   type: slack-notification
#   source:
#     url: https://hooks.slack.com/services/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

jobs:

- name: rally_init
  plan:
  - aggregate:
    - get: git-osp
      trigger: true
    - get: rally_test
    - get: git-semver
      params: {bump: patch}
  - task: propagate_rally_tests
    # privileged: true
    file: git-osp/09.rally/build_tasks/propagate_rally_tests.yml
    params:
      OS_AUTH_URL: {{OS_AUTH_URL}}
      OS_USERNAME: {{OS_USERNAME}}
      OS_PASSWORD: {{OS_PASSWORD}}
      OS_TENANT_NAME: {{OS_TENANT_NAME}}
  - put: rally_test
    params: {repository: propagated_tests}
  - put: git-semver
    params: {file: git-semver/version}