resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest


resources:

- name: git-resource_osp
  type: git
  source:
    uri: {{git-uri_osp}}
    branch: master
    private_key: {{git-private-key}}

- name: git-resource_test-result
  type: git
  source:
    uri: {{git-uri_test-result}}
    branch: gh-pages
    private_key: {{git-private-key}}

- name: git-resource_build
  type: git
  source:
    uri: {{git-uri_test-result}}
    branch: build
    private_key: {{git-private-key}}

- name: git-resource_semver
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri_test-result}}
    branch: version
    file: version
    private_key: {{git-private-key}}

- name: slack-resource
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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


jobs:

- name: Functional-Test
  public: true
  plan:
  - aggregate:
    - get: git-resource_osp
      trigger: true
    - get: git-resource_semver
    - get: git-resource_build
  - task: tempest-test
    file: git-resource_osp/08.tempest/build_tasks/tempest_test.yml
    params:
      ANSIBLE_HOST_KEY_CHECKING: 'false'
      REDHAT_USER_NAME: {{REDHAT_USER_NAME}}
      REDHAT_USER_PWD: {{REDHAT_USER_PWD}}
      REDHAT_REG_POOLID: {{REDHAT_REG_POOLID}}
      REDHAT_REPO_ENABLED: {{REDHAT_REPO_ENABLED}}
      OS_AUTH_URL: {{OS_AUTH_URL}}
      OS_USERNAME: {{OS_USERNAME}}
      OS_PASSWORD: {{OS_PASSWORD}}
      OS_TENANT_NAME: {{OS_TENANT_NAME}}
  - put: git-resource_build
    params: {repository: tempest_output}

- name: Build-Plane
  public: true
  plan:
  - aggregate:
    - get: git-resource_osp
    - get: git-resource_semver
    - get: git-resource_build
      trigger: true
      passed: [Functional-Test]
    - get: git-resource_test-result
  - task: parse-tempest-logs
    file: git-resource_osp/08.tempest/build_tasks/build_plane.yml
  - put: git-resource_test-result
    params: {repository: tempest_parsed_result}
  - put: git-resource_build
    params: {repository: git-resource_build_clean}

- name: Slack-Notify
  public: true
  plan:
  - get: git-resource_semver
    passed: [Functional-Test, Build-Plane]
  - put: slack-resource
    params:
      channel: '#ci_message'
      icon_emoji: ':robot_face:'
      # text: The newest version is deployed!
      # text_file: git-resource_semver/version
      # text_file: tempest_output/slack_message.txt
      text: |
        Tempest Result Link: https://godleon.github.io/osp_test_results/$(cat git-resource_semver/version)/tempest.html
        You can also download the compressed Tempest detail logs at:
        https://github.com/godleon/osp_test_results/raw/gh-pages/$(cat git-resource_semver/version)/ra-out.txt

        The build had a result. Check it out at:
        http://10.5.17.254:8080/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        or at: 
        http://10.5.17.254:8080/builds/$BUILD_ID
  - put: git-resource_semver
    params: {bump: patch, file: git-resource_semver/version}

# - name: rally-test
#   public: true
#   plan:
#   - get: osp_test_resource
#     trigger: true
#     passed: [tempest]
#       params:
#       bump: minor
#     rc: true
#   - task: rally
#     file: osp_test_resource/06.osp10_tempest_rally/build_tasks/rally_test.yml

# - name: Increasing-Version-Number
#   plan:
#   - get: git-resource_semver
#     trigger: true
#     params: {bump: patch}
#     passed: [Slack-Notify]
#   - put: git-resource_semver
#     params: {bump: patch, file: git-resource_semver/version}
#   - task: display-version
#     config:
#       platform: linux
#       image_resource:
#         type: docker-image
#         source: {repository: busybox}
#       inputs:
#       - name: git-resource_semver
#       run:
#         path: cat
#         args: [git-resource_semver/version]