resources:
- name: osp_test_resource
  type: git
  source:
    uri: https://github.com/godleon/concourse_ci_lab
    branch: master

jobs:
- name: Run Tempest Test
  plan:
  - get: osp_test_resource
    trigger: true
  - task: Run Tempest
    file: osp_test_resource/03.osp10_tempest/build_tasks/build.yml