resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest


resources:

- name: git-resource_osp
  type: git
  source:
    uri: {{git-uri-osp}}
    branch: master
    private_key: {{git-private-key}}

- name: git-resource_semver
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri-test_result}}
    branch: version
    file: version
    private_key: {{git-private-key}}

- name: slack-resource
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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


jobs:

- name: Functional-Test
  public: true
  plan:
  - get: git-resource_osp
    trigger: true
  - get: git-resource_semver
    trigger: true
    params: {bump: patch}
  - task: tempest-test
    file: git-resource_osp/08.slack_alert/build_tasks/tempest_test.yml
#   - put: tempest_output
#   - task: debug_task
#     file: osp_test_resource/07.slack_notification/build_tasks/debug_task.yml

- name: Slack-Notify
  public: true
  plan:
  - get: git-resource_semver
    trigger: true
    passed: [Functional-Test]
  - put: slack-resource
    params:
      channel: '#ci_message'
      icon_emoji: ':robot_face:'
      # text: The newest version is deployed!
      text_file: git-resource_semver/version
      # text_file: tempest_output/slack_message.txt
      # text: |
      #   The build had a result. Check it out at:
      #   http://10.5.17.254:8080/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      #   or at: 
      #   http://10.5.17.254:8080/builds/$BUILD_ID

      #   Result: "Slack Result!"
        
        #$TEXT_FILE_CONTENT
  # - put: git-resource_semver
  # params: {bump: patch, file: resource-version/version}

# - name: rally-test
#   public: true
#   plan:
#   - get: osp_test_resource
#     trigger: true
#     passed: [tempest]
#       params:
#       bump: minor
#     rc: true
#   - task: rally
#     file: osp_test_resource/06.osp10_tempest_rally/build_tasks/rally_test.yml