resources:
- name: resource-version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri}}
    branch: version
    file: version
    private_key: {{git-private-key}}


jobs:
- name: job-versioning-1
  # public: true
  # serial: true
  plan:
  - get: resource-version
    trigger: true
    params: {bump: patch}
      # pre: rc
  - task: display-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: resource-version
      run:
        path: cat
        args: [resource-version/version]
  - put: resource-version
    params: {bump: patch, file: resource-version/version}

- name: job-versioning-2
  # public: true
  # serial: true
  plan:
  - get: resource-version
    trigger: true
    passed: [job-versioning-1]
    params: {bump: patch}
    #   pre: rc
  - task: display-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: resource-version
      run:
        path: cat
        args: [resource-version/version]
